sudo: true
language: node_js
node_js:
  - "8"
cache: yarn
env:
  global:
    COMMIT=${TRAVIS_COMMIT::8}

before_install: sudo apt-get install -y createrepo dpkg-dev apt-utils gnupg2 gzip
before_script: cp config.template.js config.js
script: yarn lint && yarn build-server && yarn test

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=atlassian/nucleus
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO